//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iReverse_MTP_Bypass_Universal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iReverse_MTP_Bypass_Universal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_libusb_1_0_x86 {
            get {
                object obj = ResourceManager.GetObject("amd64_libusb_1_0_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_libusb0 {
            get {
                object obj = ResourceManager.GetObject("amd64_libusb0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_libusb0_sys {
            get {
                object obj = ResourceManager.GetObject("amd64_libusb0_sys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_libusb0_x86 {
            get {
                object obj = ResourceManager.GetObject("amd64_libusb0_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_libusbK {
            get {
                object obj = ResourceManager.GetObject("amd64_libusbK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_libusbK_sys {
            get {
                object obj = ResourceManager.GetObject("amd64_libusbK_sys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_libusbK_x86 {
            get {
                object obj = ResourceManager.GetObject("amd64_libusbK_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_WdfCoInstaller01009 {
            get {
                object obj = ResourceManager.GetObject("amd64_WdfCoInstaller01009", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_WdfCoInstaller01011 {
            get {
                object obj = ResourceManager.GetObject("amd64_WdfCoInstaller01011", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] amd64_winusbcoinstaller2 {
            get {
                object obj = ResourceManager.GetObject("amd64_winusbcoinstaller2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cat_SAMSUNG {
            get {
                object obj = ResourceManager.GetObject("cat_SAMSUNG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cat_SAMSUNG_Android {
            get {
                object obj = ResourceManager.GetObject("cat_SAMSUNG_Android", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cyggcc_s_1 {
            get {
                object obj = ResourceManager.GetObject("cyggcc_s_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cyggcs_s_1 {
            get {
                object obj = ResourceManager.GetObject("cyggcs_s_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cygusb_1_0 {
            get {
                object obj = ResourceManager.GetObject("cygusb_1_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cygwin1 {
            get {
                object obj = ResourceManager.GetObject("cygwin1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iconireverse {
            get {
                object obj = ResourceManager.GetObject("iconireverse", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] install_x64 {
            get {
                object obj = ResourceManager.GetObject("install_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] install_x86 {
            get {
                object obj = ResourceManager.GetObject("install_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] linux_adk {
            get {
                object obj = ResourceManager.GetObject("linux_adk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; SAMSUNG.inf
        ///; Copyright (c) 2010-2016 Pete Batard &lt;pete@akeo.ie&gt; (GNU LGPL)
        ///[Strings]
        ///DeviceName = &quot;SAMSUNG&quot;
        ///VendorName = &quot;Samsung Electronics Co., Ltd&quot;
        ///SourceName = &quot;SAMSUNG Install Disk&quot;
        ///DeviceID   = &quot;#DeviceID#&quot;
        ///DeviceGUID = &quot;{f72fe0d4-cbcb-407d-8814-9ed673d0dd6b}&quot;
        ///
        ///[Version]
        ///Signature   = &quot;$Windows NT$&quot;
        ///Class       = &quot;USBDevice&quot;
        ///ClassGuid   = {88bae032-5a81-49f0-bc3d-a4ff138216d6}
        ///Provider    = &quot;libwdi&quot;
        ///CatalogFile = SAMSUNG.cat
        ///DriverVer   = 08/09/2018, 6.1.7600.16385
        ///
        ///[ClassInstall3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAMSUNG {
            get {
                return ResourceManager.GetString("SAMSUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Copyright (c) 2011 libusbK (GNU LGPL)
        ///;
        ///; Module Name: SAMSUNG_Android.inf
        ///; Description: Installation inf for SAMSUNG_Android device.
        ///;
        ///; THIS CODE AND INFORMATION IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY
        ///; KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
        ///; IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
        ///; PURPOSE.
        ///
        ///[Strings]
        ///DeviceName = &quot;SAMSUNG_Android&quot;
        ///VendorName = &quot;Samsung Electronics Co., Ltd&quot;
        ///SourceName = &quot;SAMSUNG_Android Install Disk&quot;
        ///DeviceID   = &quot;#Dev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAMSUNG_Android {
            get {
                return ResourceManager.GetString("SAMSUNG_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] x86_libusb0 {
            get {
                object obj = ResourceManager.GetObject("x86_libusb0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] x86_libusb0_sys {
            get {
                object obj = ResourceManager.GetObject("x86_libusb0_sys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] x86_libusb0_x86 {
            get {
                object obj = ResourceManager.GetObject("x86_libusb0_x86", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] x86_libusbK {
            get {
                object obj = ResourceManager.GetObject("x86_libusbK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] x86_libusbK_sys {
            get {
                object obj = ResourceManager.GetObject("x86_libusbK_sys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] x86_WdfCoInstaller01009 {
            get {
                object obj = ResourceManager.GetObject("x86_WdfCoInstaller01009", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] x86_WdfCoInstaller01011 {
            get {
                object obj = ResourceManager.GetObject("x86_WdfCoInstaller01011", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] x86_winusbcoinstaller2 {
            get {
                object obj = ResourceManager.GetObject("x86_winusbcoinstaller2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
